### PR TITLE
Bup performance work

### PR DESCRIPTION
**Pull request by dpc**

### CODE REVIEW

**Comment by dpc** [comment]
Before:

```
test bup::tests::bup_perf_1mb ... bench:      31,320 ns/iter (+/- 1,602)                                                
```

After:

```
test bup::tests::bup_perf_1mb ... bench:      25,747 ns/iter (+/- 1,014)                                                
```

**Comment by aidanhs** [comment]
Sorry for not getting to this for a few days, I thought it would require more review than it actually did!

Looks good to me, but I am wondering why you've put the benchmarks behind a feature flag?

**Comment by dpc** [comment]
Benchmarks don't work on `stable` AFAIK. So feature flag prevents breaking `stable` compilation.

**Comment by aidanhs** [comment]
Ahh ok, I live on nightly :)

Ok, I've added you as a collaborater on the repo and on crates.io as discussed. When convenient, can you merge this PR and publish a new version to check it's all working ok?

I've pushed a couple of minor cosmetic changes I'd made locally, and I've discovered I have some benchmark reworking locally that I'll rebase on top of your changes at some point after you merge.

**Comment by dpc** [comment]
Thanks!

**Pull request merged**
