### PR TITLE
Implement Gear CDC

### PR DESCRIPTION
**Pull request by dpc**
```
    Implement Gear CDC
    
    Implemented as per my understanding of:
    
    FastCDC: a Fast and Efficient Content-Defined Chunking Approach for Data
    Deduplication
    
    https://www.usenix.org/system/files/conference/atc16/atc16-paper-xia.pdf
    
    and
    
    "Ddelta: A deduplication-inspired fast delta compression approach"
    
    Note: this does not yet implement FastCDC, only the Gear portion of it.
    
    Random numbers were generated locally from `/dev/urandom` and since
    it's not cryptographic hash, I don't think anyone cares.
```

### CODE REVIEW

**Comment by dpc** [comment]
This is on top of #5 

```
test bup::tests::bup_perf_1mb   ... bench:   2,392,759 ns/iter (+/- 79,120)
test gear::tests::gear_perf_1mb ... bench:   1,725,285 ns/iter (+/- 75,486)
```

In my benchmarks for rdedup, this yields same space results as `bup` and when chunking is the bottleneck, it improves the performance, lowering the total deduplication time up to 50%.

**Comment by aidanhs** [comment]
I'll give the paper and this implementation a read through at some point in the next week.

Are you aware of any existing implementations of this? I like to be able to test against other people's code when possible.

Some links for my own reference:
 - https://webcourse.cs.technion.ac.il/236834/Spring2017/ho/WCFiles/PE14-Ddelta-GearBased.pdf (gear chunking pdf link)
 - https://github.com/netleibi/fastchunking/issues/2

**Comment by dpc** [comment]
I wasn't able to find anything other than the whitepapers. For something so fundamentally simple, it is surprising.

**Comment by aep** [comment]
@dpc   thanks alot.  in my tests, the implementation performs about 1% faster but with 1% worse compression than bup. Is that consistent with  your experience or am i using it wrong?

**Comment by dpc** [comment]
@aep In my tests ( rdedup + https://github.com/gilbertchen/benchmarking on my desktop) the storage stayed the same (but it is printed as 1.4G, so I wouldn't notice 1% difference, I guess), and some backup iterations were much faster.

I don't know how are you testing it. It's important to make sure that CDC was actually your bottleneck. `rdedup` with `-vv` will dump time spent statistics for every thread, and CDC ("chunking") is actually commonly the bottleneck, especially now that I've implemented blake2b for hashing, and `zstd` for compression.

**Comment by aep** [comment]
@dpc thanks for sharing.  our bottleneck is actually the spinning over each byte single threaded.  I'll look at how you designed that.

Storage is the biggest worry though. Since you already did the research, can you recommend a cdc that is optimized for space?

**Comment by dpc** [comment]
I am a fairly fresh in this, so please treat everything I say with a grain of salt: from my experience and knowledge, specific CDC algorithm does not influence deduplication ratio that much. 

In https://www.usenix.org/node/196197 there are multiple references to some other CDCs, that I had no time to read yet. However, it seems to me that CDC's speed is typically the important aspect because it needs to go through all the data, at all times.

Chunk size is the most important deduplication ratio parameter. If your data changes in a lot of places, but by a small amount (example: source code), making your chunks as small as practically possible matters a lot. Small chunks, however, mean a lot of small files, which is not great for synchronization or offloading to the cloud (more requests). Also, the compression works better on bigger chunks. 2K average chunk size is practical minimum, I believe (especially without compression asymmetric encryption overhead in rdedup). 64K is a safe size on the low end of the size spectrum. 1MB are big chunks, that are more useful for cloud storage.

After that, the easiest way to lower the storage requirements is to use better compression. In `rdedup` there is already like 5 compression algorithms one can pick from, and some (like `xz2`, are quite slow, but compress stuff really well).

`rdedup`'s gitter channel is a place where more people doing something with deduplication can be found, you can try asking there too.

**Comment by aidanhs** [comment]
@aep fyi, you can parallelise splitting (assuming your IO can keep up). Mentioned at https://github.com/dpc/rdedup/pull/91#issuecomment-289778137:

> you can actually parallelise rolling checksums - pick a few offsets (call them 'superchunks') and run the rolling sum from each of the locations, populating a vector with the splits from each offset. Since the splits depend only on the N bytes at that location, they can be used regardless of where the rollsum started from. Two things to be aware of though - the superchunks must overlap to check for a split location straddling a superchunk boundary, and you need to handle splitting too-large chunks very carefully

**Comment by aep** [comment]
@aidanhs that is very useful information, thanks a ton!
I'll be optimizing storage first. so far a simple test with a large image shows only 1% reused when the image shifts 2px right, so i must be using it wrong. https://github.com/aep/sixpool/blob/master/cafs/src/serializer.rs#L96   

actually i just checked and rdup has exactly the same issue.
(rust_versions is two rust binaries from the same source code)
```
aep@derp: ~ rdedup -d /tmp/asd/  init --compression none
Enter new passphrase: 
Enter new passphrase again: 
aep@derp: ~ rdup -x /dev/null proj/sixpool/cafs/test/rust_versions  | rdedup -d /tmp/asd store blaasdzxzxc
47 new chunks
6767370 new bytes
aep@derp: ~ du -h proj/sixpool/cafs/test/rust_versions
6.5M	proj/sixpool/cafs/test/rust_versions
aep@derp: ~ 
```

**Comment by dpc** [comment]
@aep CDC-based deduplication works by finding exactly same sequences bytes in data. Modifed images only appear similar. Shifting and image will completely change its byte structure, especially if it's a compressed format (mosts are). Dedupcliation would work if you tried eg. multiple tar images, containing mostly the same files (like images).

**Pull request merged**
