### PR TITLE
Add `Bup::new_with_chunk_bits` to support custom chunk sizes

### PR DESCRIPTION
**Pull request by dpc**
This is to make the suggestion from #3 more ergonomic.

### CODE REVIEW

**Comment by dpc** [comment]
@aidanhs Ping.

**Comment by aidanhs** [comment]
@dpc merged, version bumped, released, docs bumped.

As an aside, it's a little naughty to change the license of a project (rdedup) without checking with contributors. Though since I appear to be the only one who's contributed code and my contributions were pretty minor, it's not a big deal.

**Comment by dpc** [comment]
@aidanhs: You're right. Sorry for that. I plan to revert to the original anyway, after I gave it some thought. Part of the reason is that accepting contributions would be hard. My motives were/are complicated. Seems like no solution is satisfying. Ultimately I'd like to run Open Source projects like companies-in-the-open, and just grant contributors shares in the project. I'm actually still pursuing / researching the area...

Anyway, thanks!

**Comment by aidanhs** [comment]
> Seems like no solution is satisfying.

I agree, it's a difficult situation that I've struggled with before. I personally think I lean towards the AGPL for binaries like rdedup, and if companies wanted it licensed under something else and make closed source changes, they can pay for it. However, this requires a transfer of copyright (end of http://producingoss.com/en/copyright-assignment.html) for any contributors.

**Pull request merged**
