### PR TITLE
Some improvements.

### PR DESCRIPTION
**Pull request by dpc**
Add a handy makefile with `publishdoc`, `cargo check` support, etc.

Add  documentation over public API.

Use `trait` to support other rolling sums.

Use ranges, Options, iterators and other Rusty things.

I'm open to discuss the change - I don't think I necessarily did a perfect job.

### CODE REVIEW

**Comment by aidanhs** [comment]
@dpc thanks! Out of curiosity, are you using this for something?

However, unless I'm missing something I think there's a file missing from this PR? I assume `lib/bup.rs`.

**Comment by dpc** [comment]
Oops. Should be there now.

I'm thinking about writing a tool that like more unix-spirited version of zbackup/[ddar](https://github.com/basak/ddar/) that takes stream input, chunks it, and runs through command line (to run through xz and gpg2). And the other way around.

**Comment by aidanhs** [comment]
Thanks for the PR! I made a minor followup change to remove a stray type parameter - https://github.com/aidanhs/rsroll/commit/d6aab400d07e547015e46d7bdb7a4f048e1ce3de

There's ~2% regression in performance according to my benchmarks, which I guess is down to the simplifications in the bit twiddling and passing a function to find chunk edges. I have no issues with that, just want to note it for the record.

**Comment by aidanhs** [comment]
The docs are now published - the makefile was indeed handy!

I've published version 0.2.0 to crates.io, and I've made a couple of other tweaks. The only one related to this PR is that I renamed `CHUNK_SIZE_LOG2` back to `CHUNK_BITS` - I can see what you're getting at, but it is actually used as a bitmask.

**Comment by dpc** [comment]
Ack. :)

**Comment by dpc** [comment]
The performance difference might be due to change in the chunk edge condition. It used to do some shortcut on s1 and s2, and now it uses full digest().

**Comment by aidanhs** [comment]
Possibly, and it may also struggle to inline the condition check. Honestly it's a readability win so I haven't been motivated to look into it.

**Comment by dpc** [comment]
Hey @aidanhs . I have an alpha version of rdedup working: https://github.com/dpc/rdedup so I'm just pinging you that I'm using rsroll there and seems to be working fine for me so far.

**Comment by aidanhs** [comment]
:+1:

**Pull request merged**
